language: scala
scala:
- 2.11.8
dist: trusty
jdk: openjdk8
sudo: false
cache:
  directories:
  - $HOME/.sbt/0.13
  - $HOME/.sbt/boot/scala*
  - $HOME/.sbt/cache
  - $HOME/.sbt/launchers
  - $HOME/.ivy2
before_cache:
- du -h -d 1 $HOME/.ivy2/
- du -h -d 2 $HOME/.sbt/
- find $HOME/.sbt -name "*.lock" -type f -delete
- find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete
env:
  matrix:
  - TRAVIS_NESTED_LAMBDA=facia-purger
script: cd $TRAVIS_NESTED_LAMBDA && sbt ++$TRAVIS_SCALA_VERSION clean test riffRaffUpload
