name: Build Facia Purger
on:
  push:
    paths:
      - 'cdk/**'
      - 'facia-purger/**'
  workflow_dispatch:
jobs:
  facia-purger:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "corretto"
      - uses: actions/setup-node@v3
        with:
          node-version-file: "./cdk/.nvmrc"
      - working-directory: ./cdk
        run: |
          npm ci
          npm run lint
          npm test
          npm run synth
      - name: clean, compile, test, assemble jar, copy to root dir
        working-directory: ./facia-purger
        run: |
          sbt -v clean compile test assembly
          cp target/scala*/facia-purger.jar .
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.GU_RIFF_RAFF_ROLE_ARN }}
          aws-region: eu-west-1
      - name: Upload to Riff-Raff
        uses: guardian/actions-riff-raff@v2.2.2
        with:
          projectName: facia-purger
          configPath: facia-purger/riff-raff.yaml
          buildNumberOffset: 88
          contentDirectories: |
            cloudformation:
              - cdk/cdk.out/FaciaPurger-CODE.template.json
              - cdk/cdk.out/FaciaPurger-PROD.template.json
            facia-purger:
              - facia-purger.jar
            
