name: Build Backup Parameter Store
on:
  push:
    paths:
      - '.github/**'
      - 'backup-parameter-store/**'

jobs:
  backup-parameter-store:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      pull-requests: write # Required for riff-raff action

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "corretto"

      - name: clean, compile, test assemble jar, copy to root dir
        working-directory: ./backup-parameter-store
        run: |
          sbt -v clean compile test assembly
          cp target/scala*/backup-parameter-store.jar .

      - name: Upload to Riff-Raff
        uses: guardian/actions-riff-raff@v4
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          roleArn: ${{ secrets.GU_RIFF_RAFF_ROLE_ARN }}
          projectName: dotcom:backup-parameter-store
          configPath: backup-parameter-store/riff-raff.yaml
          buildNumberOffset: 1118
          contentDirectories: |
            backup-parameter-store-cfn:
              - backup-parameter-store/cfn.yaml
            backup-parameter-store:
              - backup-parameter-store/backup-parameter-store.jar