name: Build Backup Parameter Store
on:
  push:
    paths:
      - 'backup-parameter-store/**'
jobs:
  backup-parameter-store:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "corretto"
      - name: clean, compile, test assemble jar, copy to root dir
        working-directory: ./backup-parameter-store
        run: |
          sbt -v clean compile test assembly
          cp target/scala*/backup-parameter-store.jar .
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.GU_RIFF_RAFF_ROLE_ARN }}
          aws-region: eu-west-1
      - name: Upload to Riff-Raff
        uses: guardian/actions-riff-raff@v2.2.2
        with:
          projectName: dotcom:backup-parameter-store
          configPath: backup-parameter-store/riff-raff.yaml
          buildNumberOffset: 118
          contentDirectories: |
            backup-parameter-store:
              - backup-parameter-store/backup-parameter-store.jar
              - backup-parameter-store/cfn.yaml