name: CI
on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  CI:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.GU_RIFF_RAFF_ROLE_ARN }}
          aws-region: eu-west-1
      - uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "corretto"
      - uses: actions/setup-node@v3
        with:
          node-version-file: "./cdk/.nvmrc"
      - working-directory: ./cdk
        run: |
          npm ci
          npm run lint
          npm test
          npm run synth
      - name: clean, compile, test and upload facia-purger
        if: contains(github.event.pull_request.files.*.filename, 'facia-purger/') || contains(github.event.pull_request.files.*.filename, 'facia-purger')
        working-directory: ./facia-purger
        run: |
          LAST_TEAMCITY_BUILD=88
          export GITHUB_RUN_NUMBER=$(( $GITHUB_RUN_NUMBER + $LAST_TEAMCITY_BUILD ))
          sbt -v "clean;compile;test;riffRaffUpload"
      - name: clean, compile, test and upload backup-parameter-store
        if: contains(github.event.pull_request.files.*.filename, 'backup-parameter-store/') || contains(github.event.pull_request.files.*.filename, 'backup-parameter-store')
        working-directory: ./backup-parameter-store
        run: |
          LAST_TEAMCITY_BUILD=108
          export GITHUB_RUN_NUMBER=$(( $GITHUB_RUN_NUMBER + $LAST_TEAMCITY_BUILD ))
          sbt -v "clean;compile;test;riffRaffUpload"